@extends('welcome')

@section('content')
<div style="margin: 40px 30px;">
	<label style="float: none;
    margin: 0 auto;
    display: table;">Privacy Policy </label><br/>
What is our Privacy Policy?
<p>Jobtip.in has created this Privacy Policy in order to disclose its use of personal data you give to Jobtip.in when you access or use Jobtip.in’s online and/or mobile services, web sites, and software provided on or in connection with the services or web sites (collectively, the “Website”). This Privacy Policy covers only data collected through the Website and not any other data collection or processing, including, without limitation, data collection practices of other web pages to which we link or data that we or our subsidiaries collect offline or through web sites, products, or services that do not display a direct link to this Privacy Policy. Occasionally, we may refer to this Privacy Policy in notices and consent requests related to special-purpose web pages, for example, if we invite you to submit ideas to improve the Website; under such circumstances, this Privacy Policy applies as modified in the particular notice or consent request (e.g., with respect to types of data collected or purposes of collection). Therefore, this policy describes procedures for the collection, usage and disclosure of information when you use the Website.
Besides personal data the Website is committed to diligence and for the processing and storage of all types of data related to your trade status, which you assume to provide. The Website guarantees the protection of commercial and professional secrecy and non-disclosure of information to third parties except when required by law and by authorized state or other authorities and institutions, and in subject to the condition in the next sentence. The Website reserves the right to disclose information to third parties under the terms and for the purposes referred to in detail in these General terms, which you acknowledge having become a site user.</p>

What all Information do we collect?
<p>The Website collects data when you request information, subscribe for a service, register as a user, participate in a survey, post a rating or review, add your friends,  post a job openings, skills or services, post a resume, upload content or otherwise actively send us data on our Website, we usually collect data including about your business, work experience, location, skills, educational details and others that and / or in case you choose to provide us, as well as personal data, friends information details in case you send a friend request of opt to connect with any social website plugins and / or in the event that you decide to provide us with a purpose to ensure the effective implementation of the service. The data that we can collect, consist mostly of business and professional information like trade name, company, address, UIC, legal representative / s and / or other data entered in the Commercial Register, email, professional commercial status. Information mainly consists of data about the business activity, which positions you as an employer in a particular area of the market. You voluntarily provide the data you have decided on the Website. </p>
<p>As part of the standard operation of the Website, Jobtip.in will automatically collect information from your computer or mobile device, including, but not limited to, your browser type, operating system, IP address and the domain name from which you accessed the site, and if you are accessing our site with your mobile device, type of mobile device. In addition we may record actions taken on the Website including, but not limited to, date and times of use, clicks, page views, the amount of time you spend on each page, and search queries. Jobtip.in reserves the right to match your IP address or other information with other information about you in any way permitted by applicable law. </p>
If you access or use the Website on your mobile telephone or other mobile device, including tablets, we collect mobile device identifiers, including MAC Address, and IP Address. Jobtip.in may create and assign to your device an identifier that is similar to an account number. We may collect the name you have associated with your device, device type, telephone number, country, and any other information you choose to provide, such as user name, geo-location or e-mail address. We may also access your contacts to enable you to invite friends to join you in the Website.</p>
How do we help you with collected Information?
<p>We collect information from you in order to help the process of proposing and announcing the proposal for the chosen work position as well as it’s potentially occupation. We use the data obtained in order to ensure and guarantee a better service to our users. Registering of detailed information on the Website and its disclosure to job seekers and / or persons posted their resumes on the Website and our customers, promotes the recruitment process and facilitates faster and better career opportunities for the users of the Website. We guarantee that we will not collect and process the data for purposes other than those described above without your explicit consent.
Jobtip.in uses this information and information generated when you use our Website, including but not limited to your resume, your posted reviews, searches, clicks, taps, web sites and web pages you visit through our mobile software (including third party web sites and web pages), job applications, messages and postings to provide our services and features to you, to provide your information to employers that may be interested in contacting you, to provide employer information to you and to measure and improve those services and features, and to provide you with customer support. For example, Jobtip.in uses your previous search history and the jobs you click on to determine relevant search results and provide you with recommended jobs. It will help you in content filtering and serve us to publish relevant job information to users. If you are located in the India, Jobtip.in may also share your personal information, such as your email address, with third party websites and/or social networking sites in order to show you targeted advertisements and other content that has been customized for you. Jobtip.in may also use the information to prevent potentially illegal activities and activities that are detrimental to you or other users.</p> 
<p>Where this is necessary, the Website reserves the right to transfer the data wholly or partly to third parties who help us in data processing and / or finding job candidates with the aim to achieve consideration of proposed by us job offers. We also reserve the right to share information with selected third parties which we think would stimulate the professional development of companies and occupation for the published work position, provided to us by them. We undertake not to disclose parts or any information you provide to third parties who in any way are not linked to the process of recruitment or would not contribute in any way to accomplish the aforementioned objectives.</p>
<p>Jobtip.in may investigate and disclose information from or about you or your use of Jobtip.in if we have a good faith belief that such investigation or disclosure is (a) reasonably necessary to comply with legal process and law enforcement instructions and orders; (b) helpful to prevent, investigate, or identify possible wrongdoing in connection with the use of the Website; or (c) protects our rights, reputation, property, safety, or that of the public. We may use a variety of methods to detect and address anomalous activity and screen content to prevent abuse such as spam. These efforts may on occasion result in a temporary or permanent suspension or termination of some functions for some users. Jobtip.in may use your IP address and mobile device information to help diagnose problems with Jobtip.in’s service and to administer Jobtip.in’s site. Your IP address and mobile device information may also be used to help identify you, your location, and your online profile and to gather broad demographic information (such as country of origin). Jobtip.in may maintain (as permitted by applicable law) your data following your termination of your relationship with Jobtip.in. Jobtip.in may delete your user data as permitted by applicable law.</p> 
<p>Yes, you can be contacted.
When you give Jobtip.in contact information (such as your name, email address or phone number) and demographic information, you agree that Jobtip.in may utilize this information as set forth herein. You can secure your phone or email address to stop spamming and unnecessary calls but friends in your connection can access your details. All your posts can be shared to other social websites or via emails by your friends. You agree that Jobtip.in may, as part of its services to you, communicate with you, or initiate communication with you on behalf of a 3rd party, through your Jobtip.in account or through other means made available through your contact information such as email, phone, or postal mail. If and to the extent permitted by applicable law, Jobtip.in, or its designated third party partners, may also use your contact information to send you job alerts, create an account, send you information about Jobtip.in and if you are located in the INDIA, send you promotional material from some of Jobtip.in’s partners. Jobtip.in may use demographic and/or profile data to tailor your experience on Jobtip.in’s site, show you content that Jobtip.in thinks you may be interested in, and display content according to your preferences. Your personal information gets placed on the Jobtip.in Website when you upload or edit a resume. To the extent you upload a resume or edit it, and subject to your Privacy Settings, you are making the resume, your name and other personal information that you place on your resume available to third parties who may be interested in you as an employee, search engines, or to the general public by posting your personal information on the internet. You acknowledge that Jobtip.in may note if the words of your resume match the words of certain job descriptions, if you use your resume to apply for a job through Jobtip.in Apply, in order to improve service to job seekers and employers. If you post a public resume, this may be crawled by, and displayed through, search engines when someone searches for your name. This means that third parties can view the personal information contained in your resume and you may receive unsolicited contact from parties unaffiliated with Jobtip.in and for whom Jobtip.in has no responsibility. If you do not want your personal information posted on the Website, you should not upload it. You may opt-out of this feature by editing your Privacy Settings; however, Jobtip.in does not warrant how often third-party search engines will update their caches, which may contain old public resume information. Jobtip.in reserves the right to charge third parties a fee for accessing your information as part of Jobtip.in’s services. At your direction, Jobtip.in may also send your resume to third parties if you choose to apply for a job listing.</p>
 How do we ensure security of your data?
<p>The security of your data is extremely important to us. Access to your information is granted only to our employees and third parties who assist us in the processing of these data. The Website is not responsible for the authenticity and identity of the data. You decide which and what data to provide. In case of abuse, we expect you to immediately notify us!</p>
<p>The Website has security measures in place to protect the loss, misuse and alteration of the information under Jobtip.in’s control. Jobtip.in uses SSL encryption, access control policies, anti-virus programs and firewalls to protect information under our control. No method of transmission over the Internet, or method of electronic storage, is 100% secure, however. In addition, please note that emails, messages sent via your web browser, and other similar means of communication with other users are not encrypted. We strongly advise you not to communicate any confidential information through these means. Therefore, while we strive to protect your information, we cannot guarantee its security.</p>
How Cookies help us to help you?
<p>"Cookies" are a way to keep some amount of personal information. We use so-called "cookies" to keep your user name and details about what type of job you offer. We may use cookies to manage our users’ sessions and to store preferences, tracking information, and language selection. Cookies may be used whether you register with us or not. "Cookies" are small text files transferred by a web server to your hard drive and thereafter stored on your computer. The types of information a cookie collects include the date and time you visited, your browsing history, your preferences, and your username. In some instances, our third-party service providers may use cookies on the Website. We cannot control or access cookies used by third- party service providers. This Privacy Policy covers only Cookies used by us, and not any cookies used by third parties. You have the ability to either accept or decline the use of cookies on your computer, whether you are registered with us or not. Typically, you can configure your browser to not accept cookies. </p>
In what circumstances we can Disclose Information?
<p>On rare occasions, we may be required to disclose your personal information due to legal or regulatory requirements. In such instances, we reserve the right to disclose your personal information as required in order to comply with our legal obligations, including but not limited to complying with court orders, warrants, subpoenas, service of process requirements, or discovery requests. We may also disclose information about our users to law enforcement officers or others, in the good faith belief that such disclosure is reasonably necessary to enforce these Terms and/or Privacy Policy; respond to claims that any Content violates the rights of third-parties; or protect the rights, property, or personal safety of Jobtip.in, our users or the general public. You agree and acknowledge that we may not inform you prior to or after disclosures made according to this section. If substantially all of our assets are sold or merged into another company, we will notify you of the transaction. The acquiring company shall be given access to your personal information without your consent. If we sell only a part of our business, the acquiring entity shall have access to your personal information without your consent and we may send you a notice regarding this sale.</p>
How will you know about our Privacy Policy Changes?
<p>We reserve the right to change these Terms from time to time, and at our sole discretion. We may send you a notice regarding material changes to these Terms, including the Privacy Policy or the Website. You should make note of the "last updated date" at the beginning of the Terms. With this information, you should be able to identify if the Terms have been updated recently.</p>
How to Contact Us to discuss Disputes?
<p>Any disputes regarding your privacy are subject to the Terms, including but not limited to any provisions related to indemnification, limitations on damages, and choice of law. If you have questions about this Privacy Policy, please contact Jobtip.in via the Legal Issues report form with "Privacy Policy" in the subject line.
We welcome your Feedback, Questions and Recommendations.
</p>
</div>

@stop